### ISSUE TITLE
Weather Dashboard: Libray Issue

### ISSUE THREAD

**Issue by Simmarith** [ttn-muc/promini-node-sketches#1]
The Project under /weather_dashboard does not work with the latest version(2.3.0) of the BME280 Library

Error code: exit status 1
'TempUnit_Celcius' is not a member of 'BME280'
The Issue appears to be in line 151

Happy fixing ;D

**Comment by c7h** [comment]
It seems you have a typo: it's called `TempUnit_Celsius`
